<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Motoroute Login')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
  <!-- plugins:css -->
  <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('node_modules/flag-icon-css/css/flag-icon.min.css'))
            ->prependStylesheet($this->basePath('node_modules/simple-line-icons/css/simple-line-icons.css'))
            ->prependStylesheet($this->basePath('node_modules/mdi/css/materialdesignicons.min.css'))
        ?>
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <?= $this->headLink()->prependStylesheet($this->basePath('css/style.css'))?>
  <!-- endinject -->
  

    
</head>

<body>

    <body>
        <div class="container-scroller">
            <div class="container-fluid page-body-wrapper">
                <?=$this->content;?>
                <!-- row ends -->
            </div>
            <!-- page-body-wrapper ends -->
        </div>
        <!-- container-scroller -->
        <!-- plugins:js -->
        
        <?= $this->headScript()
            ->prependFile($this->basePath('js/off-canvas.js'))
            ->prependFile($this->basePath('js/misc.js'))
            ->prependFile($this->basePath('node_modules/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('node_modules/popper.js/dist/umd/popper.min.js'))
            ->prependFile($this->basePath('node_modules/jquery/dist/jquery.min.js'))
        ?>
        
        <!-- endinject -->
        
    </body>

</html>